/*
 * File: app/model/Person.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.model.Person', {
    extend: 'Ext.data.Model',

    uses: [
        'Simplereg.model.Contact'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'version',
            type: 'int'
        },
        {
            name: 'firstName',
            type: 'string'
        },
        {
            name: 'lastName',
            type: 'string'
        },
        {
            dateFormat: 'd.m.Y',
            name: 'dateOfBirth',
            type: 'date'
        },
        {
            name: 'ssn',
            type: 'string'
        },
        {
            name: 'gender',
            type: 'string'
        }
    ],

    hasMany: {
        model: 'Simplereg.model.Contact',
        foreignKey: 'personId',
        name: 'contacts'
    },

    validations: [
        {
            type: 'presence',
            field: 'firstName'
        },
        {
            type: 'presence',
            field: 'lastName'
        },
        {
            type: 'presence',
            field: 'genger'
        },
        {
            type: 'inclusion',
            field: 'genger',
            list: [
                'MALE',
                'FEMALE',
                'UNKNOWN'
            ]
        }
    ]
});