/*
 * File: app/model/Contact.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.model.Contact', {
    extend: 'Ext.data.Model',

    uses: [
        'Simplereg.model.Person'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'version',
            type: 'int'
        },
        {
            name: 'personId',
            type: 'int'
        },
        {
            name: 'ctype',
            type: 'string'
        },
        {
            name: 'countryCode',
            type: 'string'
        },
        {
            name: 'address',
            type: 'string'
        },
        {
            name: 'phoneNumber',
            type: 'string'
        }
    ],

    belongsTo: {
        associationKey: 'person',
        model: 'Simplereg.model.Person',
        foreignKey: 'person_id',
        getterName: 'getPerson',
        setterName: 'setPerson'
    },

    validations: [
        {
            type: 'presence',
            field: 'type'
        },
        {
            type: 'presence',
            field: 'address'
        },
        {
            type: 'inclusion',
            field: 'type',
            list: [
                'HOME',
                'BUSINESS',
                'ABROAD'
            ]
        }
    ]
});