/*
 * File: app/view/Page.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simpleauth.view.Page', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Simpleauth.view.UserList',
        'Simpleauth.view.UserRoleList',
        'Simpleauth.view.RoleList'
    ],

    id: 'Page',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'pages',
                    activeTab: 0,
                    deferredRender: false,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'border'
                            },
                            title: 'Users',
                            items: [
                                {
                                    xtype: 'userlist',
                                    header: false,
                                    flex: 3,
                                    region: 'center',
                                    split: true,
                                    splitterResize: false
                                },
                                {
                                    xtype: 'panel',
                                    flex: 2,
                                    region: 'east',
                                    split: true,
                                    splitterResize: false,
                                    id: 'UserDetail',
                                    width: 150,
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'userrolelist',
                                            frame: true,
                                            margin: 5
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Roles',
                            items: [
                                {
                                    xtype: 'rolelist',
                                    header: false,
                                    flex: 1
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            cls: 'thick',
                            hidden: true,
                            itemId: 'main',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'System',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                action: 'quit',
                                                text: 'Quit'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});
