/*
 * File: app/view/UserCreate.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simpleauth.view.UserCreate', {
    extend: 'Ext.window.Window',

    requires: [
        'Simpleauth.view.toolbar.OkCancelReset'
    ],

    id: 'UserCreate',
    itemId: 'dialog',
    width: 400,
    closeAction: 'hide',
    iconCls: 'icon-add',
    title: 'Add User',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'Data',
                    api: { submit: "authWeb.createAuthUser" },
                    standardSubmit: false,
                    trackResetOnLoad: true,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Username',
                            name: 'username',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Password',
                            name: 'password',
                            inputType: 'password'
                        },
                        {
                            xtype: 'textfield',
                            matchFieldName: 'password',
                            anchor: '100%',
                            fieldLabel: 'Confirm',
                            name: 'passwordCfm',
                            submitValue: false,
                            inputType: 'password',
                            validateBlank: true,
                            vtype: 'match'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Name',
                            name: 'name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Email',
                            name: 'email',
                            vtype: 'email'
                        }
                    ]
                },
                {
                    xtype: 'toolbarokcancelreset'
                }
            ]
        });

        me.callParent(arguments);
    }

});