#release configuration
#Thu Aug 28 12:31:57 CEST 2025
completedPhase=create-backup-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.org.sqlproc\:sql-processor-archetypes.empty=true
project.scm.org.sqlproc\:sql-processor-beans.empty=true
project.scm.org.sqlproc\:sql-processor-parent.connection=scm\:git\:https\://github.com/hudec/sql-processor.git
project.scm.org.sqlproc\:sql-processor-parent.developerConnection=scm\:git\:https\://github.com/hudec/sql-processor.git
project.scm.org.sqlproc\:sql-processor-parent.tag=HEAD
project.scm.org.sqlproc\:sql-processor-parent.url=scm\:git\:https\://github.com/hudec/sql-processor.git
project.scm.org.sqlproc\:sql-processor-spring.empty=true
project.scm.org.sqlproc\:sql-processor.empty=true
project.scm.org.sqlproc\:sqlproc-archetype-simple-jdbc.empty=true
project.scm.org.sqlproc\:sqlproc-archetype-simple-spring.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/hudec/sql-processor.git
