/*
* generated by Xtext
*/
package org.sqlproc.dsl.ui.contentassist;

import org.sqlproc.dsl.ui.contentassist.AbstractProcessorDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProcessorDslProposalProvider extends AbstractProcessorDslProposalProvider {

}
