/*
 * generated by Xtext
 */
package org.sqlproc.dsl;

import org.sqlproc.dsl.resolver.PojoResolverFactory;
import org.sqlproc.dsl.resolver.PojoResolverFactoryBean;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProcessorDslRuntimeModule extends org.sqlproc.dsl.AbstractProcessorDslRuntimeModule {

    @Override
    public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return ProcessorNameProvider.class;
    }

    public Class<? extends PojoResolverFactory> bindPojoResolverFactory() {
        return PojoResolverFactoryBean.class;
    }
}
