/*
 * File: app/view/DialogToolbar2.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.DialogToolbar2', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.dialogtoolbar2',

    ui: 'footer',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    action: 'accept',
                    width: 70,
                    text: 'OK'
                },
                {
                    xtype: 'button',
                    action: 'cancel',
                    width: 70,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});