/*
 * File: app/view/PersonContacts.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonContacts', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.personcontacts',

    requires: [
        'Simplereg.view.ListToolbar',
        'Simplereg.view.override.PersonContacts'
    ],

    frame: true,
    itemId: 'contacts',
    title: 'Contacts',
    store: 'Contacts',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tools: [
                {
                    xtype: 'tool',
                    action: 'reload',
                    type: 'refresh'
                }
            ],
            dockedItems: [
                {
                    xtype: 'listtoolbar',
                    dock: 'top'
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    sortable: false,
                    dataIndex: 'id',
                    text: 'Id',
                    flex: 1,
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    sortable: false,
                    dataIndex: 'version',
                    text: 'Version',
                    flex: 1,
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    sortable: false,
                    dataIndex: 'personId',
                    text: 'Person Id',
                    flex: 1,
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    sortable: false,
                    dataIndex: 'ctype',
                    text: 'Type',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'title',
                    text: 'Contact',
                    flex: 2
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    sortable: false,
                    dataIndex: 'countryCode',
                    text: 'Country',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'address',
                    text: 'Address',
                    flex: 2
                },
                {
                    xtype: 'gridcolumn',
                    sortable: false,
                    dataIndex: 'phoneNumber',
                    text: 'Phone',
                    flex: 2
                }
            ]
        });

        me.callParent(arguments);
    }

});