/*
 * generated by Xtext
 */
package org.sqlproc.dsl.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.sqlproc.dsl.processorDsl.MappingRule;
import org.sqlproc.dsl.processorDsl.MetaStatement;
import org.sqlproc.dsl.processorDsl.OptionalFeature;

/**
 * customization of the default outline structure
 * 
 */
public class ProcessorDslOutlineTreeProvider extends DefaultOutlineTreeProvider {

    @Override
    public void createChildren(IOutlineNode parent, EObject modelElement) {
        if (modelElement instanceof MetaStatement)
            return;
        if (modelElement instanceof MappingRule)
            return;
        if (modelElement instanceof OptionalFeature)
            return;
        super.createChildren(parent, modelElement);
    }

}
