/*
 * generated by Xtext
 */
package org.sqlproc.dsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.sqlproc.dsl.processorDsl.Artifacts;
import org.sqlproc.dsl.processorDsl.MappingRule;
import org.sqlproc.dsl.processorDsl.MetaStatement;
import org.sqlproc.dsl.processorDsl.OptionalFeature;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ProcessorDslLabelProvider extends DefaultEObjectLabelProvider {

    @Inject
    public ProcessorDslLabelProvider(AdapterFactoryLabelProvider delegate) {
        super(delegate);
    }

    public String text(Artifacts ele) {
        return "MODEL";
    }

    public String text(MetaStatement ele) {
        return ele.getType().getName() + ": " + ele.getName();
    }

    public String text(MappingRule ele) {
        return ele.getType().getName() + ": " + ele.getName();
    }

    public String text(OptionalFeature ele) {
        return ele.getType().getName() + ": " + ele.getName();
    }

    /*
     * String image(MyModel ele) { return "MyModel.gif"; }
     */
}
