/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    stores: [
        'People',
        'Contacts',
        'Gender',
        'ContactType'
    ],
    views: [
        'Page',
        'ContactAdd',
        'ContactList',
        'ContactDelete',
        'ContactModify'
    ],
    autoCreateViewport: true,
    controllers: [
        'Person'
    ],
    name: 'Simplereg',

    launch: function() {
        Ext.state.Manager.setProvider(Ext.create('Ext.state.CookieProvider'));

        // Prepare loading mask
        Ext.LOADING = new Ext.LoadMask(Ext.getBody(), {
            msg: "Loading..."
        });

        // Prepare dialogs
        Ext.create("Simplereg.view.PersonFind");
        Ext.create("Simplereg.view.PersonAdd");
        Ext.create("Simplereg.view.PersonDelete");
        Ext.create("Simplereg.view.PersonModify");

        Ext.create("Simplereg.view.ContactAdd");
        Ext.create("Simplereg.view.ContactDelete");
        Ext.create("Simplereg.view.ContactModify");

        new Ext.KeyMap(Ext.get(document), [
        // Find person (Ctrl+F)
        {
            key: "F",
            ctrl: true,
            shift: false,
            alt: false,
            fn: function(keyCode, event) {
                Ext.getCmp("PersonFind").show();
                event.stopEvent();
            }
        },
        // Refresh page (Ctrl+R)
        {
            key: "R",
            ctrl: true,
            shift: true,
            alt: false,
            fn: function(keyCode, event) {
                Simplereg.controller.Person.refreshPage();
                event.stopEvent();
            }
        }
        ]);
    }

});
