/*
 * File: app/controller/Person.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.controller.Person', {
    extend: 'Ext.app.Controller',

    statics: {
        refreshPage: function() {
            var panel = Ext.getCmp("PersonRegistry"),
                view = panel.getActiveTab();

            // Person selection
            if (view.is("personselection")) {
                Simplereg.controller.Person.refreshPersonSelection();
            }

            // Person view
            else {
                Simplereg.controller.Person.refreshPersonView(view);
            }
        },

        identifyPersonView: function(id) {
            return "PersonView" + id;
        },

        titlePersonView: function(record) {
            var data = record.data,
                text = [], title;

            // Person name
            text.push(data.firstName + " " + data.lastName);

            // Person identification
            if (data.ssn) {
                text.push(data.ssn);
            }

            title = text.join(" | ");
            return title;
        },

        openPersonView: function(id, refresh) {
            var panel = Ext.getCmp("PersonRegistry"),
                ident = Simplereg.controller.Person.identifyPersonView(id),
                view = panel.child("#" + ident);

            // Create new view
            if (!view) {
                view = Ext.create("Simplereg.view.PersonView", {
                    closable: true,
                    itemId: ident
                });

                panel.add(view);

                // View store
                var store = Ext.create("Simplereg.store.People", {
                    storeId: ident + "Store"
                });

                view.store = store;

                store.proxy.extraParams = {
                    contacts: true,
                    id: id
                };

                refresh = true;
            }

            // Activate view
            panel.setActiveTab(view);

            // Refresh view
            if (refresh) {
                Simplereg.controller.Person.refreshPersonView(view);
            }
        },

        closePersonView: function(id) {
            var panel = Ext.getCmp("PersonRegistry"),
                ident = Simplereg.controller.Person.identifyPersonView(id),
                view = panel.child("#" + ident);

            // Close person view
            if (view && view.closable) {
                view.close();
            }
        },

        refreshPersonSelection: function() {
            var panel = Ext.getCmp("PersonRegistry"),
                view = panel.child("personselection"),
                grid = view.down("#person_list"),
                store = grid.getStore();

            // Refresh
            store.reload();

            grid.getSelectionModel().deselectAll();

        },

        refreshPersonView: function(view, record) {
            // Refresh from store
            if (!record) {
                var store = view.store;

                Ext.LOADING.show();

                store.load({
                    callback: function(records, operation, success) {
                        if (success) {
                            Simplereg.controller.Person.refreshPersonView(view, records[0]);
                        }
                        Ext.LOADING.hide();
                        return success;
                    }
                });
            }

            // Refresh from record
            else {
                view.record = record;

                // Set title
                var title = Simplereg.controller.Person.titlePersonView(record);
                view.setTitle(title);

                document.title = title;

                // Fill person detail
                var person = view.down("persondetail form");
                person.loadRecord(record);

                // Fill contacts
                var grid = view.down("contactlist grid"),
                    store = record.contacts();

                grid.bindStore(store);
                grid.getSelectionModel().deselectAll();

                // Paging toolbar
                var toolbar = grid.down("pagingtoolbar");
                if (toolbar) {
                    toolbar.bindStore(store);
                    store.totalCount = store.data.items.length;
                    toolbar.onLoad();
                }
            }
        },

        findPersonFromDialog: function() {
            var dialog = Ext.getCmp("PersonFind"),
                form = dialog.down("form");

            if (!form.isValid()) {
                return false;
            }

            // Activate selection tab
            var panel = Ext.getCmp("PersonRegistry"),
                view = panel.child("personselection");

            panel.setActiveTab(view);

            // Person list
            var values = form.getValues(),
                grid = view.down("grid"),
                store = grid.getStore();

            store.proxy.extraParams = values;

            store.load({
                callback: function(records, operation, success) {
                    store.totalCount = records.length;
                    grid.down("pagingtoolbar").onLoad();
                }
            });

            dialog.close();
        },

        addPersonFromDialog: function(source) {
            var dialog = Ext.getCmp("PersonAdd"),
                form = dialog.down("form");

            if (!form.isValid()) {
                return false;
            }

            // Create new person
            simpleService.createPerson(source, {
                success: function(result) {
                    Simplereg.controller.Person.refreshPersonSelection();
                    Simplereg.controller.Person.openPersonView(result.id);
                    form.getForm().reset();
                    dialog.close();
                },
                failure: function(result) {
                    ;
                }
            });
        },

        updatePersonFromDialog: function(source) {
            var dialog = Ext.getCmp("PersonModify"),
                form = dialog.down("form");

            if (!form.isValid()) {
                return false;
            }

            // Update person
            simpleService.updatePerson(source, {
                success: function(result) {
                    Simplereg.controller.Person.refreshPersonSelection();
                    Simplereg.controller.Person.openPersonView(result.id, true);
                    form.getForm().reset();
                    dialog.close();
                },
                failure: function(result) {
                    ;
                }
            });
        },

        deletePersonFromDialog: function(source) {
            var dialog = Ext.getCmp("PersonDelete");

            // Delete person
            simpleService.deletePerson(source, {
                success: function(result) {
                    Simplereg.controller.Person.refreshPersonSelection();
                    Simplereg.controller.Person.closePersonView(result.id);
                    dialog.close();
                },
                failure: function(result) {
                    ;
                }
            });
        },

        addContactFromDialog: function(source) {
            var dialog = Ext.getCmp("ContactAdd"),
                form = dialog.down("form");

            dialog.disable();

            if (!form.isValid()) {
                return false;
            }

            // Create new contact
            simpleService.createContact(source, {
                success: function(result) {
                    Simplereg.controller.Person.refreshPage();
                    form.getForm().reset();
                    dialog.close();
                },
                failure: function(result) {
                    ;
                }
            });

            dialog.enable();
        },

        updateContactFromDialog: function(source) {
            var dialog = Ext.getCmp("ContactModify"),
                form = dialog.down("form");

            if (!form.isValid()) {
                return false;
            }

            // Update contact
            simpleService.updateContact(source, {
                success: function(result) {
                    Simplereg.controller.Person.refreshPage();
                    form.getForm().reset();
                    dialog.close();
                },
                failure: function(result) {
                    ;
                }
            });
        },

        deleteContactFromDialog: function(source) {
            var dialog = Ext.getCmp("ContactDelete"),
                form = dialog.down("form");

            if (!form.isValid()) {
                return false;
            }

            // Delete contact
            simpleService.deleteContact(source, {
                success: function(result) {
                    Simplereg.controller.Person.refreshPage();
                    dialog.close();
                },
                failure: function(result) {
                    ;
                }
            });
        }
    },

    onPersonRegistryRender: function(component, eOpts) {
        // Set document title
        var view = component.getActiveTab(),
            title = view.title;

        document.title = title;
    },

    onPersonRegistryTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        // Set document title
        var title = newCard.title;

        document.title = title;
    },

    onRefreshPageClick: function(button, e, eOpts) {
        Simplereg.controller.Person.refreshPage();
    },

    onClosePageClick: function(button, e, eOpts) {
        var panel = Ext.getCmp("PersonRegistry"),
            view = panel.getActiveTab();

        // Close view
        if (view && view.closable) {
            view.close();
        }
    },

    onResetDialogClick: function(button, e, eOpts) {
        var dialog = button.up("window"),
            form = dialog.down("form");

        form.getForm().reset();
    },

    onSubmitDialogClick: function(button, e, eOpts) {
        var dialog = button.up("window"),
            form = dialog.down("form");

        form.submit();
    },

    onCancelDialogClick: function(button, e, eOpts) {
        var dialog = button.up("window");

        dialog.close();
    },

    onPersonFindClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("PersonFind");

        dialog.show();
    },

    onPersonAddClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("PersonAdd");

        dialog.show();
    },

    onPersonModifyClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("PersonModify"),
            form = dialog.down("form"),
            record = button.up("personview").record;

        if (!record) {
            return false;
        }

        // Fill form
        form.loadRecord(record);

        dialog.show();
    },

    onPersonDeleteClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("PersonDelete"),
            form = dialog.down("form"),
            record = button.up("personview").record;

        if (!record) {
            return false;
        }

        // Fill form
        form.loadRecord(record);

        dialog.show();
    },

    onSelectedPersonDeleteClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("PersonDelete"),
            form = dialog.down("form"),
            selection = button.up("personselection").down("#person_list").getSelectionModel().getSelection(),
            record = selection ? selection[0] : null;

        if (!record) {
            return false;
        }

        // Fill form
        form.loadRecord(record);

        dialog.show();
    },

    onPersonOpenClick: function(button, e, eOpts) {
        var selection = button.up("personselection").down("#person_list").getSelectionModel().getSelection(),
            record = selection ? selection[0] : null;

        if (!record) {
            return false;
        }

        // Open selected person
        Simplereg.controller.Person.openPersonView(record.data.id);
    },

    onPersonListDblClick: function(dataview, record, item, index, e, eOpts) {
        Simplereg.controller.Person.openPersonView(record.data.id);
    },

    onPersonListSelectionchange: function(model, selected, eOpts) {
        var panel = Ext.getCmp("PersonSelection"),
            toggle = selected.length ? "enable" : "disable";

        // Toggle enable/disable
        panel.down("#selected_person_delete")[toggle]();
        panel.down("#person_open")[toggle]();
    },

    onContactAddClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("ContactAdd"),
            form = dialog.down("form"),
            record = button.up("personview").record;

        if (!record) {
            return false;
        }

        form.record = record;

        // Fill form
        form.down("#person_id").setValue(record.data.id);

        dialog.show();
    },

    onSelectedContactModifyClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("ContactModify"),
            form = dialog.down("form"),
            selection = button.up("contactlist").down("#contact_list").getSelectionModel().getSelection(),
            record = selection ? selection[0] : null;

        if (!record) {
            return false;
        }

        // Fill form
        form.loadRecord(record);

        dialog.show();
    },

    onSelectedContactDeleteClick: function(button, e, eOpts) {
        var dialog = Ext.getCmp("ContactDelete"),
            form = dialog.down("form"),
            selection = button.up("contactlist").down("#contact_list").getSelectionModel().getSelection(),
            record = selection ? selection[0] : null;

        if (!record) {
            return false;
        }

        // Fill form
        form.loadRecord(record);

        dialog.show();
    },

    onContactListItemDblClick: function(dataview, record, item, index, e, eOpts) {

    },

    onContactListSelectionChange: function(model, selected, eOpts) {
        var panel = Ext.getCmp("PersonRegistry"),
            view = panel.getActiveTab(),
            grid = view.down("contactlist #contact_list"),
            toggle = selected.length ? "enable" : "disable";

        if (grid.getSelectionModel() != model) {
            return false;
        }

        // Toggle enable/disable
        view.down("#selected_contact_delete")[toggle]();
        view.down("#selected_contact_modify")[toggle]();
    },

    init: function(application) {
        this.control({
            "#PersonRegistry": {
                render: this.onPersonRegistryRender,
                tabchange: this.onPersonRegistryTabChange
            },
            "#refresh_page": {
                click: this.onRefreshPageClick
            },
            "#close_page": {
                click: this.onClosePageClick
            },
            "#reset_dialog": {
                click: this.onResetDialogClick
            },
            "#submit_dialog": {
                click: this.onSubmitDialogClick
            },
            "#cancel_dialog": {
                click: this.onCancelDialogClick
            },
            "#person_find": {
                click: this.onPersonFindClick
            },
            "#person_add": {
                click: this.onPersonAddClick
            },
            "#person_modify": {
                click: this.onPersonModifyClick
            },
            "#person_delete": {
                click: this.onPersonDeleteClick
            },
            "#selected_person_delete": {
                click: this.onSelectedPersonDeleteClick
            },
            "#person_open": {
                click: this.onPersonOpenClick
            },
            "#person_list": {
                itemdblclick: this.onPersonListDblClick,
                selectionchange: this.onPersonListSelectionchange
            },
            "#contact_add": {
                click: this.onContactAddClick
            },
            "#selected_contact_modify": {
                click: this.onSelectedContactModifyClick
            },
            "#selected_contact_delete": {
                click: this.onSelectedContactDeleteClick
            },
            "#contact_list": {
                itemdblclick: this.onContactListItemDblClick,
                selectionchange: this.onContactListSelectionChange
            }
        });
    }

});
