/*
 * File: app/view/ContactList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.ContactList', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contactlist',

    frame: true,
    margin: 5,
    title: 'Contact List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'contact_add',
                            iconCls: 'icon-add',
                            text: 'Add'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'selected_contact_delete',
                            iconCls: 'icon-delete',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'selected_contact_modify',
                            iconCls: 'icon-edit',
                            text: 'Modify'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'contact_list',
                    store: 'Contacts',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'version',
                            text: 'Id',
                            flex: 1,
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'personId',
                            hideable: false,
                            text: 'Person Id',
                            flex: 1,
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'version',
                            text: 'Version',
                            flex: 1,
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ctype',
                            text: 'Type',
                            flex: 2
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'address',
                            text: 'Address',
                            flex: 3
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'phoneNumber',
                            text: 'Phone',
                            flex: 2
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            disabled: true,
                            displayInfo: true,
                            store: 'Contacts'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});