/*
 * File: app/view/ContactUpdate.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.ContactUpdate', {
    extend: 'Ext.window.Window',

    id: 'ContactUpdate',
    width: 400,
    closeAction: 'hide',
    iconCls: 'icon-edit',
    title: 'Modify Contact',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    defaults: {
                        anchor: '1'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: 'Contact Data',
                    api: { submit: "Simplereg.controller.Person.updateContactFromDialog" },
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Id',
                            name: 'id',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Person Id',
                            name: 'personId',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Version',
                            name: 'version',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Type',
                            name: 'ctype',
                            allowBlank: false,
                            editable: false,
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'ContactType',
                            valueField: 'value'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Address',
                            name: 'address'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Phone',
                            name: 'phoneNumber'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'reset_dialog',
                                    iconCls: 'icon-reset',
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancel_dialog',
                                    iconCls: 'icon-cancel',
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'submit_dialog',
                                    iconCls: 'icon-edit',
                                    text: 'Modify Contact'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    bussy: function(msg) {
        var me = this, bussy;

        if (!me.bussyMask) {
            me.bussyMask = new Ext.LoadMask({
                msg: "Processing...",
                target: me
            });
        }

        if (msg == undefined || msg === true) {
            bussy = true;
        }
        else if (!msg) {
            bussy = false;
        }
        else {
            me.bussyMask.msg = msg;
            bussy = true;
        }

        if (bussy) {
            me.bussyMask.show();
        }
        else {
            me.bussyMask.hide();
        }

        return bussy;
    }

});