/*
 * File: app/view/PersonData.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonData', {
    extend: 'Ext.form.Panel',
    alias: 'widget.persondata',

    frame: true,
    itemId: 'data',
    bodyPadding: 10,
    title: 'Personal Data',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    cls: 'thin',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'update-person',
                            iconCls: 'icon-edit',
                            text: 'Modify'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Id',
                    name: 'id',
                    readOnly: true
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Version',
                    name: 'version',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'First Name',
                    name: 'firstName'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Last Name',
                    name: 'lastName'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    itemId: 'date',
                    fieldLabel: 'Date of Birth',
                    name: 'dateOfBirth'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'SSN',
                    name: 'ssn'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Gender',
                    name: 'gender'
                }
            ]
        });

        me.callParent(arguments);
    }

});