/*
 * File: app/view/PersonDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonDetail', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.persondetail',

    frame: true,
    margin: 5,
    autoScroll: true,
    title: 'Person Detail',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'person_update',
                            iconCls: 'icon-edit',
                            text: 'Modify'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'First Name',
                            name: 'firstName'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Last Name',
                            name: 'lastName'
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                return Ext.util.Format.dateRenderer('j.n.Y')(value);
                            },
                            fieldLabel: 'Date of Birth',
                            name: 'dateOfBirth'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'SSN',
                            name: 'ssn'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Gender',
                            name: 'gender'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});