/*
 * File: app/view/PersonSelect.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonSelect', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personselect',

    requires: [
        'Simplereg.view.PersonList'
    ],

    id: 'PersonSelect',
    layout: {
        type: 'column'
    },
    bodyPadding: 5,
    title: 'Person Select',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    cls: 'main',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'person_search',
                            iconCls: 'icon-search',
                            text: 'Find'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'refresh_page',
                            iconCls: 'icon-refresh',
                            text: 'Refresh'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'person_create',
                            iconCls: 'icon-add',
                            text: 'Add'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'personlist',
                    columnWidth: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});