/*
 * File: app/view/PersonFind.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonFind', {
    extend: 'Ext.window.Window',

    id: 'PersonFind',
    width: 400,
    closeAction: 'hide',
    iconCls: 'icon-search',
    title: 'Find Person',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    defaults: {
                        anchor: '1'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: 'Personal Data',
                    api: { submit: "Simplereg.controller.Person.findPersonFromDialog" },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'First Name',
                            name: 'firstName'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Last Name',
                            name: 'lastName'
                        },
                        {
                            xtype: 'fieldcontainer',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            fieldLabel: 'Date of Birth',
                            items: [
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    fieldLabel: 'Date of Birth from',
                                    hideLabel: true,
                                    name: 'dateOfBirthFrom',
                                    format: 'd.m.Y'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 10',
                                    fieldLabel: '',
                                    value: '-'
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    fieldLabel: 'Date of Birth to',
                                    hideLabel: true,
                                    name: 'dateOfBirthTo',
                                    format: 'd.m.Y'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'SSN',
                            name: 'ssn'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Gender',
                            name: 'gender',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'Gender',
                            valueField: 'value'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'reset_dialog',
                                    iconCls: 'icon-reset',
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancel_dialog',
                                    iconCls: 'icon-cancel',
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'submit_dialog',
                                    iconCls: 'icon-search',
                                    text: 'Find Person'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});