/*
 * File: app/view/PersonView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personview',

    requires: [
        'Simplereg.view.PersonDetail',
        'Simplereg.view.ContactList'
    ],

    layout: {
        type: 'column'
    },
    bodyPadding: 5,
    header: false,
    title: 'Person',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    cls: 'main',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'person_find',
                            iconCls: 'icon-search',
                            text: 'Find'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'refresh_page',
                            iconCls: 'icon-refresh',
                            text: 'Refresh'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'person_add',
                            iconCls: 'icon-add',
                            text: 'Add'
                        },
                        {
                            xtype: 'button',
                            itemId: 'person_delete',
                            iconCls: 'icon-delete',
                            text: 'Delete'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'close_page',
                            text: 'Close'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'persondetail',
                    columnWidth: 0.5
                },
                {
                    xtype: 'contactlist',
                    columnWidth: 0.5
                }
            ]
        });

        me.callParent(arguments);
    }

});