/*
 * File: app/view/PersonCreate.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonCreate', {
    extend: 'Ext.window.Window',

    id: 'PersonCreate',
    width: 400,
    closeAction: 'hide',
    iconCls: 'icon-add',
    title: 'Add Person',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    defaults: {
                        anchor: '1'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: 'Personal Data',
                    api: { submit: "Simplereg.controller.Person.createPersonFromDialog" },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'First Name',
                            name: 'firstName'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Last Name',
                            name: 'lastName',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Date of Birth',
                            name: 'dateOfBirth',
                            altFormats: 'j.n.Y|d.m.Y|j.m.Y|d.n.Y|Y-m-d',
                            format: 'j.n.Y'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'SSN',
                            name: 'ssn'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Gender',
                            name: 'gender',
                            allowBlank: false,
                            editable: false,
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'Gender',
                            valueField: 'value'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'reset_dialog',
                                    iconCls: 'icon-reset',
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancel_dialog',
                                    iconCls: 'icon-cancel',
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'submit_dialog',
                                    iconCls: 'icon-add',
                                    text: 'Add Person'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    bussy: function(msg) {
        var me = this, bussy;

        if (!me.bussyMask) {
            me.bussyMask = new Ext.LoadMask({
                msg: "Processing...",
                target: me
            });
        }

        if (msg == undefined || msg === true) {
            bussy = true;
        }
        else if (!msg) {
            bussy = false;
        }
        else {
            me.bussyMask.msg = msg;
            bussy = true;
        }

        if (bussy) {
            me.bussyMask.show();
        }
        else {
            me.bussyMask.hide();
        }

        return bussy;
    }

});