/*
 * File: app/view/PersonList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonList', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personlist',

    frame: true,
    margin: 5,
    title: 'Person List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'person_add',
                            iconCls: 'icon-add',
                            text: 'Add'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            hidden: true,
                            itemId: 'selected_person_delete',
                            iconCls: 'icon-delete',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'person_open',
                            iconCls: 'icon-page',
                            text: 'Open Detail'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'person_list',
                    autoScroll: true,
                    header: false,
                    title: 'Person List',
                    store: 'People',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'version',
                            text: 'Id',
                            flex: 1,
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'version',
                            text: 'Version',
                            flex: 1,
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'firstName',
                            text: 'First Name',
                            flex: 2
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastName',
                            text: 'Last Name',
                            flex: 2
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'dateOfBirth',
                            text: 'Date of Birth',
                            flex: 1,
                            format: 'd.m.Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ssn',
                            text: 'SSN',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'gender',
                            text: 'Gender',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            displayInfo: true,
                            store: 'People'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});