/*
 * File: app/view/PersonDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonDetail', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.persondetail',

    requires: [
        'Simplereg.view.PersonData',
        'Simplereg.view.PersonContacts',
        'Simplereg.view.override.PersonDetail'
    ],

    itemId: 'person_detail',
    layout: {
        type: 'column'
    },
    bodyPadding: 5,
    closable: true,
    header: false,
    title: 'Person Detail',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    cls: 'thick',
                    items: [
                        {
                            xtype: 'splitbutton',
                            itemId: 'search-person',
                            iconCls: 'icon-search',
                            text: 'Find',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        itemId: 'search-all-people',
                                        text: 'Clear Filter'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'reload',
                            iconCls: 'icon-refresh',
                            text: 'Refresh'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'create-person',
                            iconCls: 'icon-add',
                            text: 'Add'
                        },
                        {
                            xtype: 'button',
                            itemId: 'delete-person',
                            iconCls: 'icon-delete',
                            text: 'Remove'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'persondata',
                    margin: 5,
                    columnWidth: 0.5
                },
                {
                    xtype: 'personcontacts',
                    margin: 5,
                    columnWidth: 0.5
                }
            ]
        });

        me.callParent(arguments);
    }

});