DROP SEQUENCE SIMPLE_SEQUENCE IF EXISTS CASCADE;

DROP TABLE BILLING_DETAILS IF EXISTS CASCADE;

DROP TABLE SUBSCRIBER IF EXISTS CASCADE;

DROP TABLE LIBRARY IF EXISTS CASCADE;

DROP TABLE PERSON_LIBRARY IF EXISTS CASCADE;

DROP TABLE BOOK IF EXISTS CASCADE;

DROP TABLE MOVIE IF EXISTS CASCADE;

DROP TABLE MEDIA IF EXISTS CASCADE;

DROP TABLE CONTACT IF EXISTS CASCADE;

DROP TABLE PERSON IF EXISTS CASCADE;

DROP FUNCTION IF EXISTS an_hour_before;

DROP PROCEDURE IF EXISTS new_person;
