#!/bin/bash

EXT=/home/hudec/soft/ext-4.2.0.663
SRC=/home/hudec/git/sql-processor/simple-samples/extjs/simpleauth
DST=src/main/webapp/
API="http://simple-backend.cfapps.io/api-debug.js?fullRouterUrl=true"

cat ${EXT}/packages/ext-theme-neptune/build/resources/ext-theme-neptune-all.css > ${DST}resources/Simpleauth-all.css
cat ${SRC}/resources/app.css >> ${DST}resources/Simpleauth-all.css

cat ${EXT}/ext-all.js > ${DST}all-classes.js
cat ${EXT}/packages/ext-theme-neptune/build/ext-theme-neptune.js >> ${DST}all-classes.js

curl ${API} >> ${DST}all-classes.js
cat ${SRC}/resources/direct.js >> ${DST}all-classes.js

cat ${SRC}/app/model/AuthRole.js >>  ${DST}all-classes.js
cat ${SRC}/app/model/AuthUser.js >>  ${DST}all-classes.js
cat ${SRC}/app/model/UserRole.js >>  ${DST}all-classes.js
cat ${SRC}/app/store/QueryAuthRoles.js >>  ${DST}all-classes.js
cat ${SRC}/app/store/AuthUsers.js >>  ${DST}all-classes.js
cat ${SRC}/app/store/AuthRoles.js >>  ${DST}all-classes.js
cat ${SRC}/app/store/UserRoles.js >>  ${DST}all-classes.js

cat ${SRC}/app/view/toolbar/AddRemoveModify.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/toolbar/OkCancel.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/toolbar/OkCancelReset.js >>  ${DST}all-classes.js

cat ${SRC}/app/view/UserList.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/RoleList.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/UserRoleList.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/Page.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/Viewport.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/UserCreate.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/UserDelete.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/UserRoleCreate.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/UserRoleDelete.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/UserUpdate.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/RoleCreate.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/RoleDelete.js >>  ${DST}all-classes.js
cat ${SRC}/app/view/RoleUpdate.js >>  ${DST}all-classes.js

cat ${SRC}/app/controller/override/Page.js >>  ${DST}all-classes.js
cat ${SRC}/app/controller/override/Page-updateroles.js >>  ${DST}all-classes.js
cat ${SRC}/app/controller/Page.js >>  ${DST}all-classes.js
cat ${SRC}/app.js >>  ${DST}all-classes.js


