/*
 * File: app/view/UserRoleCreate.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simpleauth.view.UserRoleCreate', {
    extend: 'Ext.window.Window',

    requires: [
        'Simpleauth.view.toolbar.OkCancelReset'
    ],

    id: 'UserRoleCreate',
    itemId: 'dialog',
    width: 400,
    closeAction: 'hide',
    iconCls: 'icon-add',
    title: 'Add User Role',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'Data',
                    api: { submit: "authWeb.createUserRole" },
                    standardSubmit: false,
                    trackResetOnLoad: true,
                    items: [
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'User Id',
                            name: 'authUserId',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Role',
                            name: 'authRole.id',
                            allowBlank: false,
                            displayField: 'name',
                            forceSelection: true,
                            minChars: 1,
                            queryMode: 'local',
                            queryParam: 'name',
                            store: 'QueryAuthRoles',
                            valueField: 'id'
                        }
                    ]
                },
                {
                    xtype: 'toolbarokcancelreset'
                }
            ]
        });

        me.callParent(arguments);
    }

});