/*
* generated by Xtext
*/
package org.sqlproc.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProcessorDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/sqlproc/dsl/parser/antlr/internal/InternalProcessorDsl.tokens");
	}
}
