/*
 * generated by Xtext
 */
package org.sqlproc.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.sqlproc.dsl.ui.internal.ProcessorDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProcessorDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProcessorDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProcessorDslActivator.getInstance().getInjector(ProcessorDslActivator.ORG_SQLPROC_DSL_PROCESSORDSL);
	}
	
}
