/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Person',
        'Contact'
    ],
    stores: [
        'Person',
        'Contact'
    ],
    views: [
        'Main',
        'Persons',
        'PersonList',
        'PersonDetail',
        'ContactList'
    ],
    autoCreateViewport: true,
    name: 'Simplereg',

    launch: function() {
        Ext.state.Manager.setProvider(Ext.create('Ext.state.CookieProvider'));

        Simplereg.preferences = {
            shiftPanels: true
        };

    }

});
