/*
 * File: app/view/PersonModify.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleWeb.view.contact.Edit', {
    extend : 'Ext.window.Window',

    id : 'ContactModify',
    width : 400,
    closeAction : 'hide',
    iconCls : 'icon-edit',
    title : 'Modify Contact Data',
    modal : true,
    y : 100,

    initComponent : function() {
        var me = this;

        Ext.applyIf(me, {
            items : [ {
                xtype : 'form',
                bodyPadding : 10,
                header : false,
                title : 'Contact Data',
                items : [ {
                    xtype : 'combobox',
                    name : 'ctype',
                    itemId : 'ctype',
                    fieldLabel : 'Type',
                    store : [ 'HOME', 'BUSINESS', 'ABROAD' ]
                }, {
                    xtype : 'textfield',
                    anchor : '100%',
                    itemId : 'address',
                    name : 'address',
                    fieldLabel : 'Address'
                }, {
                    xtype : 'textfield',
                    anchor : '100%',
                    itemId : 'phoneNumber',
                    name : 'phoneNumber',
                    fieldLabel : 'Phone Number'
                } ]
            } ],
            dockedItems : [ {
                xtype : 'toolbar',
                dock : 'bottom',
                items : [ {
                    xtype : 'tbfill'
                }, {
                    xtype : 'button',
                    itemId : 'cancel_dialog',
                    text : 'Cancel'
                }, {
                    xtype : 'button',
                    itemId : 'clear_dialog',
                    text : 'Clear'
                }, {
                    xtype : 'button',
                    itemId : 'accept_modify_contact',
                    iconCls : 'icon-accept',
                    text : 'Save Changes'
                } ]
            } ]
        });

        me.callParent(arguments);
    }

});