/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.Main', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Simplereg.view.Persons'
    ],

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    frame: true,
                    height: 250,
                    width: 400,
                    header: false,
                    title: 'Simple Registry',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'fit'
                            },
                            title: 'Simple Person Registry',
                            items: [
                                {
                                    xtype: 'persons1',
                                    header: false
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            html: 'OTHER REGISTRY NOT IMPLEMENTED YET',
                            bodyPadding: 10,
                            title: 'Other...'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});