/*
 * File: app/view/PersonDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.view.PersonDetail', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.persondetail',

    height: 250,
    width: 400,
    layout: {
        type: 'anchor'
    },
    title: 'Person Detail',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});