/*
 * File: app/view/toolbar/AddRemoveModify.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simpleauth.view.toolbar.AddRemoveModify', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.toolbaraddremovemodify',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    action: 'create',
                    iconCls: 'icon-add',
                    text: 'Add'
                },
                {
                    xtype: 'button',
                    action: 'delete',
                    iconCls: 'icon-delete',
                    text: 'Remove'
                },
                {
                    xtype: 'button',
                    action: 'update',
                    iconCls: 'icon-edit',
                    text: 'Modify'
                }
            ]
        });

        me.callParent(arguments);
    }

});