/*
 * File: app/store/Contacts.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.store.Contacts', {
    extend: 'Ext.data.Store',

    requires: [
        'Simplereg.model.Contact'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Simplereg.model.Contact',
            storeId: 'contacts',
            data: [
                {
                    id: 1,
                    personId: 1,
                    type: 'HOME',
                    address: 'Říčany'
                },
                {
                    id: 2,
                    personId: 1,
                    type: 'BUSINESS',
                    address: 'Praha',
                    phoneNumber: '+420123456789'
                },
                {
                    id: 3,
                    personId: 2,
                    type: 'HOME',
                    address: 'Prčice'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});