/*
 * File: app/store/People.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Simplereg.store.People', {
    extend: 'Ext.data.Store',

    requires: [
        'Simplereg.model.Person'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Simplereg.model.Person',
            storeId: 'people',
            data: [
                {
                    id: 1,
                    firstName: 'Jan',
                    lastName: 'Novák',
                    genger: 'MALE',
                    ssn: '012345/6789'
                },
                {
                    id: 2,
                    firstName: 'Josef',
                    lastName: 'Čapek',
                    genger: 'MALE'
                },
                {
                    id: 3,
                    firstName: 'Jana',
                    lastName: 'Nováková',
                    genger: 'FEMALE'
                },
                {
                    id: 4,
                    firstName: 'Petr',
                    lastName: 'Pavel',
                    genger: 'MALE'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});