/*
* generated by Xtext
*/
package org.sqlproc.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ProcessorDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.sqlproc.dsl.ui.internal.ProcessorDslActivator.getInstance().getInjector("org.sqlproc.dsl.ProcessorDsl");
	}
	
}
